const jsonSample = require('./sample.json')
const puppeteer = require('puppeteer');
const chromium = require("@sparticuz/chromium");

const EDITOR_STYLES = `
<style>

@import url('https://fonts.cdnfonts.com/css/roboto');
@import url('https://fonts.cdnfonts.com/css/andale-mono');
@import url('https://fonts.cdnfonts.com/css/arial-2');
@import url('https://fonts.cdnfonts.com/css/antiqua-2');
@import url(https://db.onlinewebfonts.com/c/7cc6719bd5f0310be3150ba33418e72e?family=Comic+Sans+MS);
@import url(https://db.onlinewebfonts.com/c/72c75860d89e91a517dfb1e7d308c180?family=Courier+New);
@import url(https://db.onlinewebfonts.com/c/7dca09e227fdfe16908cebb4244589e4?family=Georgia);
@import url(https://db.onlinewebfonts.com/c/5c5a257758cff0acee4d28ff555f3bc5?family=Helvetica);
@import url(https://db.onlinewebfonts.com/c/771d2d395300ea1b80c34ba5282bf694?family=Impact);
@import url(https://db.onlinewebfonts.com/c/39a0230c9a2f421123a02f97cd0d451e?family=symbol);
@import url(https://db.onlinewebfonts.com/c/cd0381aa3322dff4babd137f03829c8c?family=Tahoma);
@import url('https://fonts.cdnfonts.com/css/terminal');
@import url('https://fonts.cdnfonts.com/css/times-new-roman');
@import url('https://fonts.cdnfonts.com/css/trebuchet-ms-2');
@import url('https://fonts.cdnfonts.com/css/verdana');
@import url(https://db.onlinewebfonts.com/c/41520189ce8c64a5b902302c16e2b97b?family=Webdings+V2);
@import url(https://db.onlinewebfonts.com/c/e991cc888d4fb544fe0a88d065ab6efc?family=Wingdings);

 
body.mce-content-body, body.print-body, .export-wrapper, .document-preview-wrapper {
   font-family: Roboto, Helvetica, Verdana, sans-serif !important;
   font-size: 14pt !important;
   height: 100%;
}


.table-field-table-wrapper {
   border: 1px solid #cfd1d9;
   border-radius: 4px;
   padding-bottom: 15px;
}
.table-field-table-wrapper .table-field-name {
   background: #e5f7e9 0% 0% no-repeat padding-box;
   padding: 5px 10px;
   font-size: 12px;
   width: auto;
   display: inline-flex;
   margin: 11px;
   border-radius: 4px;
   align-items: center;
}
.table-field-table-wrapper .table-field-name .edit-table-field, .table-field-table-wrapper .table-field-name .delete-table-field {
   color: #6f758e;
   font-size: 14px;
   margin-left: 10px;
   text-decoration: none;
}
.table-field-table-wrapper .table-field-table {
   width: 100%;
   border: 0;
}
.table-field-table-wrapper .table-field-table thead tr th {
   border: 0;
   border-right: 1px solid #cfd1d9;
   padding-left: 14px;
   text-align: left;
}
.deleted-spread-content {
   position: relative;
   background: transparent;
   text-align: center;
   width: 100%;
   padding: 20px 0;
   margin-bottom: 20px;
}
.deleted-spread-content .deleted-spread-content-title {
   font-size: 0.875rem;
   padding-bottom: 10px;
}
.primary-button, .secondary-button {
   cursor: pointer;
   background-color: #0055d5;
   border-color: #0055d5;
   padding: 0.44rem 1.25rem;
   font-size: 0.875rem;
   border-radius: 0.2rem;
   color: #fff;
   border: 1px solid transparent;
   display: inline-block;
   font-weight: 400;
   text-align: center;
   user-select: none;
   vertical-align: middle;
   text-transform: none;
   overflow: visible;
   margin: 0;
}
.secondary-button {
   background-color: #f3f4f6;
   border-color: #f3f4f6;
   color: #565d7b;
}
.btn-xx-sm {
   font-size: 0.75rem;
   padding: 0.25rem 0.75rem;
}
.form-action-icon, a.edit-spread, a.delete-spread {
   color: #565d7b;
   font-size: 16px;
   margin-left: 12px;
   text-decoration: none;
}
@media print {
   .form-action-icon, a.edit-spread, a.delete-spread {
      display: none;
  }
}
.document-preview-wrapper .form-action-icon, .document-preview-wrapper a.edit-spread, .document-preview-wrapper a.delete-spread, .document-preview-wrapper .edit-spread {
   display: none;
}
@media print {
   .edit-spread {
      display: none;
  }  
}
 
.other-field-name {
   background: #e5edfb 0% 0% no-repeat padding-box;
   border-radius: 4px;
   padding: 5px 10px;
   width: auto;
   font-size: 12px;
   align-items: center;
   display: inline-block;
}
.generated-field .table-field-table-wrapper {
   border: 1px solid #cfd1d9;
   border-radius: 4px;
   padding-bottom: 0;
}
.generated-field .table-field-table-wrapper .table-field-table {
   width: 100%;
   border: 0;
   border-radius: 4px;
}
.generated-field .table-field-table-wrapper .table-field-table thead tr th {
   padding: 14px;
   border: 0;
   text-align: left;
   border-bottom: 1px solid #cfd1d9;
}
.generated-field .table-field-table-wrapper .table-field-table thead tr th:not(:last-child) {
   border-right: 1px solid #f3f4f6;
}
.generated-field .table-field-table-wrapper .table-field-table tbody tr {
   border: 0;
}
.generated-field .table-field-table-wrapper .table-field-table tbody tr td {
   border: 0;
}
.generated-field .table-field-table-wrapper .table-field-table tbody tr td .table-field-cell-data {
   background: #f3f4f6 0% 0% no-repeat padding-box;
   border-radius: 4px;
   padding: 5px 10px;
   margin: 4px;
   width: auto;
   font-size: 12px;
   align-items: center;
   display: inline-block;
}
@media print {
   .generated-field .table-field-table-wrapper .table-field-table tbody tr td .table-field-cell-data {
      background: transparent;
  }
}
.generated-field .table-field-table-wrapper .table-field-table tbody tr td:not(:last-child) {
   border-right: 1px solid #f3f4f6;
}
.generated-field .table-field-table-wrapper .table-field-table tbody tr:not(:last-child) {
   border-bottom: 1px solid #f3f4f6;
}
.generated-field.other-field-name {
   background: #f3f4f6 0% 0% no-repeat padding-box;
   border-radius: 4px;
   padding: 5px 10px;
   font-size: 12px;
   align-items: center;
}
.generated-field.other-field-name.full-width-field, .generated-field.other-field-name[data-field-name="spreads.general.allSpreads"], .generated-field.other-field-name[data-field-name="spreads.general.borrowerSpreads"], .generated-field.other-field-name[data-field-name="spreads.general.guarantorSpreads"] {
   width: 98.2%;
}
@media print {
   .generated-field.other-field-name {
      background: transparent;
  }
}
.generated-field .custom-field-table-wrapper {
   background-color: #fff;
}
.flexi-form-record-container {
   background: #fff 0% 0% no-repeat padding-box;
   border: 1px solid #cfd1d9;
}
.flexi-form-record-container .flexi-form-record-header {
   text-align: left;
   font-weight: bold;
   font-size: 18px;
   letter-spacing: 0px;
   color: #0f1943;
   padding: 12px;
   border-bottom: 1px solid #dfe6ef;
}
.flexi-form-record-container .flexi-form-record-header .flexi-form-edit {
   float: right;
   margin-right: 16px;
}
.flexi-form-record-container .flexi-form-record-header .flexi-form-delete {
   float: right;
}
.flexi-form-record-container .flexi-form-record-sections-wrapper {
   margin: 0 10%;
   border-left: 1px solid #dfe6ef;
   border-right: 1px solid #dfe6ef;
}
.flexi-form-record-container .flexi-form-record-sections-wrapper .flexi-form-record-section .flexi-form-record-section-header {
   background: #f2f3f5 0% 0% no-repeat padding-box;
   color: #0f1943;
   padding: 9px 46px 13px 20px;
   font-weight: medium;
   font-size: 16px;
}
.flexi-form-record-container .flexi-form-record-sections-wrapper .flexi-form-record-section .flexi-form-record-section-fields {
   padding: 15px 46px 0 20px;
   font-weight: medium;
   font-size: 14px;
   color: #0f1943;
}
.flexi-form-record-container .flexi-form-record-sections-wrapper .flexi-form-record-section .flexi-form-record-section-fields .flexi-form-record-section-field {
   padding-bottom: 20px;
}
.dynamic-components-wrapper .dynamic-component-header {
   font-size: 22px;
   font-weight: bold;
   text-decoration: underline;
}
.dynamic-components-wrapper .dynamic-component-section-header {
   font-size: 20px;
   font-weight: bold;
   text-decoration: underline;
}
.dynamic-components-wrapper .dynamic-component-sub-header {
   font-size: 18px;
   font-weight: bold;
}
.dynamic-components-wrapper .each-dynamic-component-wrapper {
   display: flex;
   flex-direction: column;
   row-gap: 10px;
}
.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper {
   display: flex;
   flex-direction: row;
   flex-wrap: wrap;
   row-gap: 10px;
}
.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper .each-component-field {
   width: 33.3%;
}
.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper .each-component-field.full-width-field {
   width: 100%;
}
.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper .each-component-field.half-width-field {
   width: 50%;
}
.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper .each-component-field .each-component-field-label {
   font-size: 14px;
   font-weight: bold;
}
.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper .each-component-field .each-component-field-value {
   font-size: 14px;
}
.dynamic-components-wrapper .each-dynamic-component-wrapper .dynamic-sub-component-wrapper .dynamic-sub-component-body {
   display: flex;
   flex-direction: column;
   row-gap: 10px;
}
.export-wrapper .form-action-icon {
   display: none;
}
.export-wrapper .edit-spread {
   display: none;
}
.export-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td .table-field-cell-data {
   background: transparent;
}
.export-wrapper .generated-field.other-field-name {
   background: transparent;
}

</style>

`

const header = `
<div style="width: 100%;">
<p style="text-align: center;"><span style="font-size: 10pt;">C<span style="font-size: 12pt;">reated By: </span></span><span class="other-field-name mceNonEditable generated-field" data-field-name="formsManager.formDocument.general.formDocumentCreatedBy" data-field-details="%7B%22templateDetails%22:%7B%22formTemplateId%22:1000622,%22formTemplateUniqueId%22:%22XYZ01000622FORMT%22,%22formTemplateName%22:%22forms-manger-cm-sprint3%22,%22formTemplateDescription%22:%22huh%22,%22formTemplateType%22:%22Credit%20Memo%22,%22formTemplateStyle%22:%22Ym9keS5tY2UtY29udGVudC1ib2R5LGJvZHkucHJpbnQtYm9keSwuZXhwb3J0LXdyYXBwZXIsLmRvY3VtZW50LXByZXZpZXctd3JhcHBlcntmb250LWZhbWlseTpSb2JvdG8sSGVsdmV0aWNhLFZlcmRhbmEsc2Fucy1zZXJpZiAhaW1wb3J0YW50O2ZvbnQtc2l6ZToxNHB0ICFpbXBvcnRhbnQ7aGVpZ2h0OjEwMCV9Ym9keS5tY2UtY29udGVudC1ib2R5IC5lZGl0b3ItdGFibGUgdHIgdGQsYm9keS5wcmludC1ib2R5IC5lZGl0b3ItdGFibGUgdHIgdGQsLmV4cG9ydC13cmFwcGVyIC5lZGl0b3ItdGFibGUgdHIgdGQsLmRvY3VtZW50LXByZXZpZXctd3JhcHBlciAuZWRpdG9yLXRhYmxlIHRyIHRke2hlaWdodDoyNXB4fS50YWJsZS1maWVsZC10YWJsZS13cmFwcGVye2JvcmRlcjoxcHggc29saWQgI2NmZDFkOTtib3JkZXItcmFkaXVzOjRweDtwYWRkaW5nLWJvdHRvbToxNXB4O2ZvbnQtc2l6ZToxMnB4fS50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC5lZGl0LXRhYmxlLWZpZWxkLC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC5kZWxldGUtdGFibGUtZmllbGR7Y29sb3I6IzZmNzU4ZTtwYWRkaW5nOjVweCAwO2ZvbnQtc2l6ZToxNXB4O21hcmdpbi1yaWdodDouNWVtO3RleHQtZGVjb3JhdGlvbjpub25lfS50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC1uYW1le2JhY2tncm91bmQ6I2U1ZjdlOSAwJSAwJSBuby1yZXBlYXQgcGFkZGluZy1ib3g7cGFkZGluZzo1cHggMTBweDtmb250LXNpemU6MTJweDt3aWR0aDphdXRvO2Rpc3BsYXk6aW5saW5lLWZsZXg7bWFyZ2luOjExcHg7Ym9yZGVyLXJhZGl1czo0cHg7YWxpZ24taXRlbXM6Y2VudGVyfS50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC1uYW1lIC50b29sdGlwLWNvbnRhaW5lcntwb3NpdGlvbjpyZWxhdGl2ZTttYXJnaW4tbGVmdDo4cHg7Y3Vyc29yOnBvaW50ZXJ9LnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLW5hbWUgLnRvb2x0aXAtdGV4dHt2aXNpYmlsaXR5OmhpZGRlbjt3aWR0aDoxNTBweDtiYWNrZ3JvdW5kLWNvbG9yOiMwZjE5NDM7Y29sb3I6I2ZmZjt0ZXh0LWFsaWduOmNlbnRlcjtwYWRkaW5nOjhweCA2cHg7Ym9yZGVyLXJhZGl1czo0cHg7cG9zaXRpb246YWJzb2x1dGU7ei1pbmRleDoxO3RvcDoxNjAlO2xlZnQ6LTcwcHg7b3BhY2l0eTowO3RyYW5zaXRpb246b3BhY2l0eSAuM3N9LnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLW5hbWUgLnRvb2x0aXAtdGV4dDo6YWZ0ZXJ7Y29udGVudDoiIjtwb3NpdGlvbjphYnNvbHV0ZTt0b3A6LTlweDtsZWZ0OjUwJTttYXJnaW4tbGVmdDotNXB4O2JvcmRlci13aWR0aDo1cHg7Ym9yZGVyLXN0eWxlOnNvbGlkO2JvcmRlci1jb2xvcjpyZ2JhKDAsMCwwLDApIHJnYmEoMCwwLDAsMCkgIzBmMTk0MyByZ2JhKDAsMCwwLDApfS50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC1uYW1lIC50b29sdGlwLWNvbnRhaW5lcjpob3ZlciAudG9vbHRpcC10ZXh0e3Zpc2liaWxpdHk6dmlzaWJsZTtvcGFjaXR5OjF9LnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxle3dpZHRoOjEwMCU7Ym9yZGVyOjB9LnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRoZWFkIHRyIHRoe2JvcmRlcjowO2JvcmRlci1yaWdodDoxcHggc29saWQgI2NmZDFkOTtwYWRkaW5nLWxlZnQ6MTRweDt0ZXh0LWFsaWduOmxlZnR9LmRlbGV0ZWQtc3ByZWFkLWNvbnRlbnR7cG9zaXRpb246cmVsYXRpdmU7YmFja2dyb3VuZDpyZ2JhKDAsMCwwLDApO3RleHQtYWxpZ246Y2VudGVyO3dpZHRoOjEwMCU7cGFkZGluZzoyMHB4IDA7bWFyZ2luLWJvdHRvbToyMHB4fS5kZWxldGVkLXNwcmVhZC1jb250ZW50IC5kZWxldGVkLXNwcmVhZC1jb250ZW50LXRpdGxle2ZvbnQtc2l6ZTouODc1cmVtO3BhZGRpbmctYm90dG9tOjEwcHh9LnByaW1hcnktYnV0dG9uLC5zZWNvbmRhcnktYnV0dG9ue2N1cnNvcjpwb2ludGVyO2JhY2tncm91bmQtY29sb3I6IzAwNTVkNTtib3JkZXItY29sb3I6IzAwNTVkNTtwYWRkaW5nOi40NHJlbSAxLjI1cmVtO2ZvbnQtc2l6ZTouODc1cmVtO2JvcmRlci1yYWRpdXM6LjJyZW07Y29sb3I6I2ZmZjtib3JkZXI6MXB4IHNvbGlkIHJnYmEoMCwwLDAsMCk7ZGlzcGxheTppbmxpbmUtYmxvY2s7Zm9udC13ZWlnaHQ6NDAwO3RleHQtYWxpZ246Y2VudGVyO3VzZXItc2VsZWN0Om5vbmU7dmVydGljYWwtYWxpZ246bWlkZGxlO3RleHQtdHJhbnNmb3JtOm5vbmU7b3ZlcmZsb3c6dmlzaWJsZTttYXJnaW46MH0uc2Vjb25kYXJ5LWJ1dHRvbntiYWNrZ3JvdW5kLWNvbG9yOiNmM2Y0ZjY7Ym9yZGVyLWNvbG9yOiNmM2Y0ZjY7Y29sb3I6IzU2NWQ3Yn0uYnRuLXh4LXNte2ZvbnQtc2l6ZTouNzVyZW07cGFkZGluZzouMjVyZW0gLjc1cmVtfS5mb3JtLWFjdGlvbi1pY29uLGEuZWRpdC1zcHJlYWQsYS5kZWxldGUtc3ByZWFke2NvbG9yOiM1NjVkN2I7Zm9udC1zaXplOjE2cHg7bWFyZ2luLWxlZnQ6MTJweDt0ZXh0LWRlY29yYXRpb246bm9uZTtjdXJzb3I6cG9pbnRlcjtiYWNrZ3JvdW5kLWNvbG9yOnJnYmEoMCwwLDAsMCkgIWltcG9ydGFudH1AbWVkaWEgcHJpbnR7LmZvcm0tYWN0aW9uLWljb24sYS5lZGl0LXNwcmVhZCxhLmRlbGV0ZS1zcHJlYWR7ZGlzcGxheTpub25lfX0uZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIC5mb3JtLWFjdGlvbi1pY29uLC5kb2N1bWVudC1wcmV2aWV3LXdyYXBwZXIgYS5lZGl0LXNwcmVhZCwuZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIGEuZGVsZXRlLXNwcmVhZCwuZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIC5lZGl0LXNwcmVhZHtkaXNwbGF5Om5vbmV9QG1lZGlhIHByaW50ey5lZGl0LXNwcmVhZHtkaXNwbGF5Om5vbmV9fS5vdGhlci1maWVsZC1uYW1le2JhY2tncm91bmQ6I2U1ZWRmYiAwJSAwJSBuby1yZXBlYXQgcGFkZGluZy1ib3g7Ym9yZGVyLXJhZGl1czo0cHg7cGFkZGluZzo1cHggMTBweDt3aWR0aDphdXRvO2ZvbnQtc2l6ZToxMnB4O2FsaWduLWl0ZW1zOmNlbnRlcjtkaXNwbGF5OmlubGluZS1ibG9ja30uZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVye2JvcmRlcjoxcHggc29saWQgI2NmZDFkOTtib3JkZXItcmFkaXVzOjRweDtwYWRkaW5nLWJvdHRvbTowfS5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxle3dpZHRoOjEwMCU7Ym9yZGVyOjA7Ym9yZGVyLXJhZGl1czo0cHh9LmdlbmVyYXRlZC1maWVsZCAudGFibGUtZmllbGQtdGFibGUtd3JhcHBlciAudGFibGUtZmllbGQtdGFibGUgdGhlYWQgdHIgdGh7cGFkZGluZzoxNHB4O2JvcmRlcjowO3RleHQtYWxpZ246bGVmdDtib3JkZXItYm90dG9tOjFweCBzb2xpZCAjY2ZkMWQ5fS5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRoZWFkIHRyIHRoOm5vdCg6bGFzdC1jaGlsZCl7Ym9yZGVyLXJpZ2h0OjFweCBzb2xpZCAjZjNmNGY2fS5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRye2JvcmRlcjowfS5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRke2JvcmRlcjowfS5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRkIC50YWJsZS1maWVsZC1jZWxsLWRhdGF7YmFja2dyb3VuZDojZjNmNGY2IDAlIDAlIG5vLXJlcGVhdCBwYWRkaW5nLWJveDtib3JkZXItcmFkaXVzOjRweDtwYWRkaW5nOjVweCAxMHB4O21hcmdpbjo0cHg7d2lkdGg6YXV0bztmb250LXNpemU6MTJweDthbGlnbi1pdGVtczpjZW50ZXI7ZGlzcGxheTppbmxpbmUtYmxvY2t9QG1lZGlhIHByaW50ey5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRkIC50YWJsZS1maWVsZC1jZWxsLWRhdGF7YmFja2dyb3VuZDpyZ2JhKDAsMCwwLDApfX0uZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC10YWJsZSB0Ym9keSB0ciB0ZDpub3QoOmxhc3QtY2hpbGQpe2JvcmRlci1yaWdodDoxcHggc29saWQgI2YzZjRmNn0uZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC10YWJsZSB0Ym9keSB0cjpub3QoOmxhc3QtY2hpbGQpIHRke2JvcmRlci1ib3R0b206MXB4IHNvbGlkICNmM2Y0ZjZ9LmdlbmVyYXRlZC1maWVsZC5vdGhlci1maWVsZC1uYW1le2JhY2tncm91bmQ6I2YzZjRmNiAwJSAwJSBuby1yZXBlYXQgcGFkZGluZy1ib3g7Ym9yZGVyLXJhZGl1czo0cHg7cGFkZGluZzo1cHggMTBweDtmb250LXNpemU6MTJweDthbGlnbi1pdGVtczpjZW50ZXJ9LmdlbmVyYXRlZC1maWVsZC5vdGhlci1maWVsZC1uYW1lLmZ1bGwtd2lkdGgtZmllbGQsLmdlbmVyYXRlZC1maWVsZC5vdGhlci1maWVsZC1uYW1lW2RhdGEtZmllbGQtbmFtZT0ic3ByZWFkcy5nZW5lcmFsLmFsbFNwcmVhZHMiXSwuZ2VuZXJhdGVkLWZpZWxkLm90aGVyLWZpZWxkLW5hbWVbZGF0YS1maWVsZC1uYW1lPSJzcHJlYWRzLmdlbmVyYWwuYm9ycm93ZXJTcHJlYWRzIl0sLmdlbmVyYXRlZC1maWVsZC5vdGhlci1maWVsZC1uYW1lW2RhdGEtZmllbGQtbmFtZT0ic3ByZWFkcy5nZW5lcmFsLmd1YXJhbnRvclNwcmVhZHMiXXt3aWR0aDo5OC4yJX1AbWVkaWEgcHJpbnR7LmdlbmVyYXRlZC1maWVsZC5vdGhlci1maWVsZC1uYW1le2JhY2tncm91bmQ6cmdiYSgwLDAsMCwwKX19LmdlbmVyYXRlZC1maWVsZCAuY3VzdG9tLWZpZWxkLXRhYmxlLXdyYXBwZXJ7YmFja2dyb3VuZC1jb2xvcjojZmZmfS5mbGV4aS1mb3JtLXJlY29yZC1jb250YWluZXJ7YmFja2dyb3VuZDojZmZmIDAlIDAlIG5vLXJlcGVhdCBwYWRkaW5nLWJveDtib3JkZXI6MXB4IHNvbGlkICNjZmQxZDl9LmZsZXhpLWZvcm0tcmVjb3JkLWNvbnRhaW5lciAuZmxleGktZm9ybS1yZWNvcmQtaGVhZGVye3RleHQtYWxpZ246bGVmdDtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZToxOHB4O2xldHRlci1zcGFjaW5nOjBweDtjb2xvcjojMGYxOTQzO3BhZGRpbmc6MTJweDtib3JkZXItYm90dG9tOjFweCBzb2xpZCAjZGZlNmVmfS5mbGV4aS1mb3JtLXJlY29yZC1jb250YWluZXIgLmZsZXhpLWZvcm0tcmVjb3JkLWhlYWRlciAuZmxleGktZm9ybS1lZGl0e2Zsb2F0OnJpZ2h0O21hcmdpbi1yaWdodDoxNnB4fS5mbGV4aS1mb3JtLXJlY29yZC1jb250YWluZXIgLmZsZXhpLWZvcm0tcmVjb3JkLWhlYWRlciAuZmxleGktZm9ybS1kZWxldGV7ZmxvYXQ6cmlnaHR9LmZsZXhpLWZvcm0tcmVjb3JkLWNvbnRhaW5lciAuZmxleGktZm9ybS1yZWNvcmQtc2VjdGlvbnMtd3JhcHBlcnttYXJnaW46MCAxMCU7Ym9yZGVyLWxlZnQ6MXB4IHNvbGlkICNkZmU2ZWY7Ym9yZGVyLXJpZ2h0OjFweCBzb2xpZCAjZGZlNmVmfS5mbGV4aS1mb3JtLXJlY29yZC1jb250YWluZXIgLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb25zLXdyYXBwZXIgLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb24gLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb24taGVhZGVye2JhY2tncm91bmQ6I2YyZjNmNSAwJSAwJSBuby1yZXBlYXQgcGFkZGluZy1ib3g7Y29sb3I6IzBmMTk0MztwYWRkaW5nOjlweCA0NnB4IDEzcHggMjBweDtmb250LXdlaWdodDptZWRpdW07Zm9udC1zaXplOjE2cHh9LmZsZXhpLWZvcm0tcmVjb3JkLWNvbnRhaW5lciAuZmxleGktZm9ybS1yZWNvcmQtc2VjdGlvbnMtd3JhcHBlciAuZmxleGktZm9ybS1yZWNvcmQtc2VjdGlvbiAuZmxleGktZm9ybS1yZWNvcmQtc2VjdGlvbi1maWVsZHN7cGFkZGluZzoxNXB4IDQ2cHggMCAyMHB4O2ZvbnQtd2VpZ2h0Om1lZGl1bTtmb250LXNpemU6MTRweDtjb2xvcjojMGYxOTQzfS5mbGV4aS1mb3JtLXJlY29yZC1jb250YWluZXIgLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb25zLXdyYXBwZXIgLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb24gLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb24tZmllbGRzIC5mbGV4aS1mb3JtLXJlY29yZC1zZWN0aW9uLWZpZWxke3BhZGRpbmctYm90dG9tOjIwcHh9LmV4cG9ydC13cmFwcGVyIC5mbGV4aS1mb3JtLXJlY29yZC1oZWFkZXIgLmZsZXhpLWZvcm0tZWRpdCwuZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIC5mbGV4aS1mb3JtLXJlY29yZC1oZWFkZXIgLmZsZXhpLWZvcm0tZWRpdHtkaXNwbGF5Om5vbmV9LmV4cG9ydC13cmFwcGVyIC5mbGV4aS1mb3JtLXJlY29yZC1oZWFkZXIgLmZsZXhpLWZvcm0tZGVsZXRlLC5kb2N1bWVudC1wcmV2aWV3LXdyYXBwZXIgLmZsZXhpLWZvcm0tcmVjb3JkLWhlYWRlciAuZmxleGktZm9ybS1kZWxldGV7ZGlzcGxheTpub25lfS5keW5hbWljLWNvbXBvbmVudHMtd3JhcHBlciAuZHluYW1pYy1jb21wb25lbnQtaGVhZGVye2ZvbnQtc2l6ZToyMnB4O2ZvbnQtd2VpZ2h0OmJvbGQ7dGV4dC1kZWNvcmF0aW9uOnVuZGVybGluZX0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmR5bmFtaWMtY29tcG9uZW50LXNlY3Rpb24taGVhZGVye2ZvbnQtc2l6ZToyMHB4O2ZvbnQtd2VpZ2h0OmJvbGQ7dGV4dC1kZWNvcmF0aW9uOnVuZGVybGluZX0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmR5bmFtaWMtY29tcG9uZW50LXN1Yi1oZWFkZXJ7Zm9udC1zaXplOjE4cHg7Zm9udC13ZWlnaHQ6Ym9sZH0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmR5bmFtaWMtY29tcG9uZW50LXN1Yi1oZWFkZXItMntmb250LXNpemU6MTZweDtmb250LXdlaWdodDpib2xkfS5keW5hbWljLWNvbXBvbmVudHMtd3JhcHBlciAuZWFjaC1keW5hbWljLWNvbXBvbmVudC13cmFwcGVye2Rpc3BsYXk6ZmxleDtmbGV4LWRpcmVjdGlvbjpjb2x1bW47cm93LWdhcDoxMHB4fS5keW5hbWljLWNvbXBvbmVudHMtd3JhcHBlciAuZWFjaC1keW5hbWljLWNvbXBvbmVudC13cmFwcGVyIC5sYWJlbC12YWx1ZS13cmFwcGVye2Rpc3BsYXk6ZmxleDtmbGV4LWRpcmVjdGlvbjpyb3c7ZmxleC13cmFwOndyYXA7cm93LWdhcDoxMHB4fS5keW5hbWljLWNvbXBvbmVudHMtd3JhcHBlciAuZWFjaC1keW5hbWljLWNvbXBvbmVudC13cmFwcGVyIC5sYWJlbC12YWx1ZS13cmFwcGVyIC5lYWNoLWNvbXBvbmVudC1maWVsZHt3aWR0aDozMy4zJX0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmVhY2gtZHluYW1pYy1jb21wb25lbnQtd3JhcHBlciAubGFiZWwtdmFsdWUtd3JhcHBlciAuZWFjaC1jb21wb25lbnQtZmllbGQuZnVsbC13aWR0aC1maWVsZHt3aWR0aDoxMDAlfS5keW5hbWljLWNvbXBvbmVudHMtd3JhcHBlciAuZWFjaC1keW5hbWljLWNvbXBvbmVudC13cmFwcGVyIC5sYWJlbC12YWx1ZS13cmFwcGVyIC5lYWNoLWNvbXBvbmVudC1maWVsZC5oYWxmLXdpZHRoLWZpZWxke3dpZHRoOjUwJX0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmVhY2gtZHluYW1pYy1jb21wb25lbnQtd3JhcHBlciAubGFiZWwtdmFsdWUtd3JhcHBlciAuZWFjaC1jb21wb25lbnQtZmllbGQgLmVhY2gtY29tcG9uZW50LWZpZWxkLWxhYmVse2ZvbnQtc2l6ZToxNHB4O2ZvbnQtd2VpZ2h0OmJvbGR9LmR5bmFtaWMtY29tcG9uZW50cy13cmFwcGVyIC5lYWNoLWR5bmFtaWMtY29tcG9uZW50LXdyYXBwZXIgLmxhYmVsLXZhbHVlLXdyYXBwZXIgLmVhY2gtY29tcG9uZW50LWZpZWxkIC5lYWNoLWNvbXBvbmVudC1maWVsZC12YWx1ZXtmb250LXNpemU6MTRweH0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmVhY2gtZHluYW1pYy1jb21wb25lbnQtd3JhcHBlciAuZHluYW1pYy1zdWItY29tcG9uZW50LXdyYXBwZXIgLmR5bmFtaWMtc3ViLWNvbXBvbmVudC1ib2R5e2Rpc3BsYXk6ZmxleDtmbGV4LWRpcmVjdGlvbjpjb2x1bW47cm93LWdhcDoxMHB4fS5leHBvcnQtd3JhcHBlciAuZm9ybS1hY3Rpb24taWNvbiwuZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIC5mb3JtLWFjdGlvbi1pY29ue2Rpc3BsYXk6bm9uZX0uZXhwb3J0LXdyYXBwZXIgLmVkaXQtc3ByZWFkLC5kb2N1bWVudC1wcmV2aWV3LXdyYXBwZXIgLmVkaXQtc3ByZWFke2Rpc3BsYXk6bm9uZX0uZXhwb3J0LXdyYXBwZXIgLmdlbmVyYXRlZC1maWVsZCAudGFibGUtZmllbGQtdGFibGUtd3JhcHBlciAudGFibGUtZmllbGQtdGFibGUgdGJvZHkgdHIgdGQsLmRvY3VtZW50LXByZXZpZXctd3JhcHBlciAuZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC10YWJsZSB0Ym9keSB0ciB0ZHtib3JkZXI6MH0uZXhwb3J0LXdyYXBwZXIgLmdlbmVyYXRlZC1maWVsZCAudGFibGUtZmllbGQtdGFibGUtd3JhcHBlciAudGFibGUtZmllbGQtdGFibGUgdGJvZHkgdHIgdGQgLnRhYmxlLWZpZWxkLWNlbGwtZGF0YSwuZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIC5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRkIC50YWJsZS1maWVsZC1jZWxsLWRhdGF7YmFja2dyb3VuZDpyZ2JhKDAsMCwwLDApfS5leHBvcnQtd3JhcHBlciAuZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC10YWJsZSB0Ym9keSB0ciB0ZDpub3QoOmxhc3QtY2hpbGQpLC5kb2N1bWVudC1wcmV2aWV3LXdyYXBwZXIgLmdlbmVyYXRlZC1maWVsZCAudGFibGUtZmllbGQtdGFibGUtd3JhcHBlciAudGFibGUtZmllbGQtdGFibGUgdGJvZHkgdHIgdGQ6bm90KDpsYXN0LWNoaWxkKXtib3JkZXItcmlnaHQ6MXB4IHNvbGlkICNmM2Y0ZjZ9LmV4cG9ydC13cmFwcGVyIC5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRkOm5vdCg6bGFzdC1jaGlsZCksLmV4cG9ydC13cmFwcGVyIC5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRkOmxhc3QtY2hpbGQsLmRvY3VtZW50LXByZXZpZXctd3JhcHBlciAuZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC10YWJsZSB0Ym9keSB0ciB0ZDpub3QoOmxhc3QtY2hpbGQpLC5kb2N1bWVudC1wcmV2aWV3LXdyYXBwZXIgLmdlbmVyYXRlZC1maWVsZCAudGFibGUtZmllbGQtdGFibGUtd3JhcHBlciAudGFibGUtZmllbGQtdGFibGUgdGJvZHkgdHIgdGQ6bGFzdC1jaGlsZHtib3JkZXItYm90dG9tOjFweCBzb2xpZCAjZjNmNGY2fS5leHBvcnQtd3JhcHBlciAuZ2VuZXJhdGVkLWZpZWxkLm90aGVyLWZpZWxkLW5hbWUsLmRvY3VtZW50LXByZXZpZXctd3JhcHBlciAuZ2VuZXJhdGVkLWZpZWxkLm90aGVyLWZpZWxkLW5hbWV7YmFja2dyb3VuZDpyZ2JhKDAsMCwwLDApfQ==%22,%22formHeaderContent%22:%22PHA+PGltZyBzcmM9Imh0dHBzOi8vbG9zdGVzdC5jeW5jc29mdHdhcmUuY29tL2RlZmF1bHQvbG9nby5wbmciIHdpZHRoPSIxMjUiIGhlaWdodD0iODAiIGFsdD0iIiBzdHlsZT0iZGlzcGxheTogYmxvY2s7IG1hcmdpbi1sZWZ0OiBhdXRvOyBtYXJnaW4tcmlnaHQ6IGF1dG87Ij48L3A+CjxwIHN0eWxlPSJ0ZXh0LWFsaWduOiBjZW50ZXI7Ij48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMHB0OyI+VGVtcGxhdGUgTmFtZTogPHNwYW4gY2xhc3M9Im90aGVyLWZpZWxkLW5hbWUgbWNlTm9uRWRpdGFibGUgIiBkYXRhLWZpZWxkLW5hbWU9ImZvcm1zTWFuYWdlci5mb3JtVGVtcGxhdGUuZ2VuZXJhbC5mb3JtVGVtcGxhdGVOYW1lIj4gRm9ybSBUZW1wbGF0ZSBOYW1lIDwvc3Bhbj4mbmJzcDs8L3NwYW4+PC9wPgo8cCBzdHlsZT0idGV4dC1hbGlnbjogY2VudGVyOyI+PHNwYW4gY2xhc3M9Im90aGVyLWZpZWxkLW5hbWUgbWNlTm9uRWRpdGFibGUgIiBkYXRhLWZpZWxkLW5hbWU9ImZvcm1zTWFuYWdlci5mb3JtVGVtcGxhdGUuZ2VuZXJhbC5mb3JtVGVtcGxhdGVOYW1lIj4gRm9ybSBUZW1wbGF0ZSBOYW1lIDwvc3Bhbj4mbmJzcDs8L3A+CjxwIHN0eWxlPSJ0ZXh0LWFsaWduOiBjZW50ZXI7Ij48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMHB0OyI+PC9zcGFuPjwvcD4=%22,%22formFooterContent%22:%22PGRpdiBzdHlsZT0id2lkdGg6IDEwMCU7Ij4KPHAgc3R5bGU9InRleHQtYWxpZ246IGNlbnRlcjsiPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IDEwcHQ7Ij5DPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogMTJwdDsiPnJlYXRlZCBCeTogPC9zcGFuPjwvc3Bhbj48c3BhbiBjbGFzcz0ib3RoZXItZmllbGQtbmFtZSBtY2VOb25FZGl0YWJsZSAiIGRhdGEtZmllbGQtbmFtZT0iZm9ybXNNYW5hZ2VyLmZvcm1Eb2N1bWVudC5nZW5lcmFsLmZvcm1Eb2N1bWVudENyZWF0ZWRCeSI+IEZvcm0gRG9jdW1lbnQgQ3JlYXRlZCBCeSA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogMTJwdDsiPiZuYnNwOyAmbmJzcDsgfCZuYnNwOyAmbmJzcDs8L3NwYW4+PHNwYW4gY2xhc3M9Im90aGVyLWZpZWxkLW5hbWUgbWNlTm9uRWRpdGFibGUiPiA8c3BhbiBjbGFzcz0icGFnZU51bWJlciI+UGFnZSBOdW1iZXIgPC9zcGFuPi88c3BhbiBjbGFzcz0idG90YWxQYWdlcyI+PC9zcGFuPiA8L3NwYW4+PC9wPgo8cCBzdHlsZT0idGV4dC1hbGlnbjogY2VudGVyOyI+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogMTBwdDsiPkN5bmMgSW5jLiB8IDQ0MzIzNDU0MzIgfCAzNTA1IEVhc3QgRnJvbnRhZ2UgUm9hZCBTdWl0ZSAxNjAxIHwmbmJzcDs8L3NwYW4+PGEgaHJlZj0iaHR0cHM6Ly93d3cuY3luY3NvZnR3YXJlLmNvbSIgc3R5bGU9ImZvbnQtc2l6ZTogMTBwdDsiPnd3dy5jeW5jc29mdHdhcmUuY29tPC9hPjxicj48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMHB0OyI+PC9zcGFuPjwvcD4KPHAgc3R5bGU9ImZvbnQtc2l6ZTogMTBwdDsgbWFyZ2luOiAxMnB4OyB0ZXh0LWFsaWduOiByaWdodDsiPjwvcD4KPHAgc3R5bGU9ImZvbnQtc2l6ZTogMTBwdDsgbWFyZ2luOiAxMnB4OyB0ZXh0LWFsaWduOiByaWdodDsiPiZuYnNwOzwvcD4KPHAgc3R5bGU9InRleHQtYWxpZ246IGNlbnRlcjsiPiZuYnNwOzwvcD4KPC9kaXY+%22,%22formHideHeader%22:false,%22formHideFooter%22:false,%22autoRegenerate%22:false,%22isActive%22:true,%22isDeleted%22:false,%22createdBy%22:%2285%22,%22createdAt%22:%222024-03-14T06:44:22.736Z%22,%22modifiedBy%22:%2285%22,%22modifiedAt%22:%222024-03-14T07:03:51.013Z%22,%22createdByName%22:%22Robin%20B%22,%22modifiedByName%22:%22Robin%20B%22%7D,%22documentDetails%22:%7B%22formDocumentName%22:%22czxvb%22,%22formTemplateId%22:1000622,%22formDocumentStyle%22:%22Ym9keS5tY2UtY29udGVudC1ib2R5LGJvZHkucHJpbnQtYm9keSwuZXhwb3J0LXdyYXBwZXIsLmRvY3VtZW50LXByZXZpZXctd3JhcHBlcntmb250LWZhbWlseTpSb2JvdG8sSGVsdmV0aWNhLFZlcmRhbmEsc2Fucy1zZXJpZiAhaW1wb3J0YW50O2ZvbnQtc2l6ZToxNHB0ICFpbXBvcnRhbnQ7aGVpZ2h0OjEwMCV9Ym9keS5tY2UtY29udGVudC1ib2R5IC5lZGl0b3ItdGFibGUgdHIgdGQsYm9keS5wcmludC1ib2R5IC5lZGl0b3ItdGFibGUgdHIgdGQsLmV4cG9ydC13cmFwcGVyIC5lZGl0b3ItdGFibGUgdHIgdGQsLmRvY3VtZW50LXByZXZpZXctd3JhcHBlciAuZWRpdG9yLXRhYmxlIHRyIHRke2hlaWdodDoyNXB4fS50YWJsZS1maWVsZC10YWJsZS13cmFwcGVye2JvcmRlcjoxcHggc29saWQgI2NmZDFkOTtib3JkZXItcmFkaXVzOjRweDtwYWRkaW5nLWJvdHRvbToxNXB4O2ZvbnQtc2l6ZToxMnB4fS50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC5lZGl0LXRhYmxlLWZpZWxkLC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC5kZWxldGUtdGFibGUtZmllbGR7Y29sb3I6IzZmNzU4ZTtwYWRkaW5nOjVweCAwO2ZvbnQtc2l6ZToxNXB4O21hcmdpbi1yaWdodDouNWVtO3RleHQtZGVjb3JhdGlvbjpub25lfS50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC1uYW1le2JhY2tncm91bmQ6I2U1ZjdlOSAwJSAwJSBuby1yZXBlYXQgcGFkZGluZy1ib3g7cGFkZGluZzo1cHggMTBweDtmb250LXNpemU6MTJweDt3aWR0aDphdXRvO2Rpc3BsYXk6aW5saW5lLWZsZXg7bWFyZ2luOjExcHg7Ym9yZGVyLXJhZGl1czo0cHg7YWxpZ24taXRlbXM6Y2VudGVyfS50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC1uYW1lIC50b29sdGlwLWNvbnRhaW5lcntwb3NpdGlvbjpyZWxhdGl2ZTttYXJnaW4tbGVmdDo4cHg7Y3Vyc29yOnBvaW50ZXJ9LnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLW5hbWUgLnRvb2x0aXAtdGV4dHt2aXNpYmlsaXR5OmhpZGRlbjt3aWR0aDoxNTBweDtiYWNrZ3JvdW5kLWNvbG9yOiMwZjE5NDM7Y29sb3I6I2ZmZjt0ZXh0LWFsaWduOmNlbnRlcjtwYWRkaW5nOjhweCA2cHg7Ym9yZGVyLXJhZGl1czo0cHg7cG9zaXRpb246YWJzb2x1dGU7ei1pbmRleDoxO3RvcDoxNjAlO2xlZnQ6LTcwcHg7b3BhY2l0eTowO3RyYW5zaXRpb246b3BhY2l0eSAuM3N9LnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLW5hbWUgLnRvb2x0aXAtdGV4dDo6YWZ0ZXJ7Y29udGVudDoiIjtwb3NpdGlvbjphYnNvbHV0ZTt0b3A6LTlweDtsZWZ0OjUwJTttYXJnaW4tbGVmdDotNXB4O2JvcmRlci13aWR0aDo1cHg7Ym9yZGVyLXN0eWxlOnNvbGlkO2JvcmRlci1jb2xvcjpyZ2JhKDAsMCwwLDApIHJnYmEoMCwwLDAsMCkgIzBmMTk0MyByZ2JhKDAsMCwwLDApfS50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC1uYW1lIC50b29sdGlwLWNvbnRhaW5lcjpob3ZlciAudG9vbHRpcC10ZXh0e3Zpc2liaWxpdHk6dmlzaWJsZTtvcGFjaXR5OjF9LnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxle3dpZHRoOjEwMCU7Ym9yZGVyOjB9LnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRoZWFkIHRyIHRoe2JvcmRlcjowO2JvcmRlci1yaWdodDoxcHggc29saWQgI2NmZDFkOTtwYWRkaW5nLWxlZnQ6MTRweDt0ZXh0LWFsaWduOmxlZnR9LmRlbGV0ZWQtc3ByZWFkLWNvbnRlbnR7cG9zaXRpb246cmVsYXRpdmU7YmFja2dyb3VuZDpyZ2JhKDAsMCwwLDApO3RleHQtYWxpZ246Y2VudGVyO3dpZHRoOjEwMCU7cGFkZGluZzoyMHB4IDA7bWFyZ2luLWJvdHRvbToyMHB4fS5kZWxldGVkLXNwcmVhZC1jb250ZW50IC5kZWxldGVkLXNwcmVhZC1jb250ZW50LXRpdGxle2ZvbnQtc2l6ZTouODc1cmVtO3BhZGRpbmctYm90dG9tOjEwcHh9LnByaW1hcnktYnV0dG9uLC5zZWNvbmRhcnktYnV0dG9ue2N1cnNvcjpwb2ludGVyO2JhY2tncm91bmQtY29sb3I6IzAwNTVkNTtib3JkZXItY29sb3I6IzAwNTVkNTtwYWRkaW5nOi40NHJlbSAxLjI1cmVtO2ZvbnQtc2l6ZTouODc1cmVtO2JvcmRlci1yYWRpdXM6LjJyZW07Y29sb3I6I2ZmZjtib3JkZXI6MXB4IHNvbGlkIHJnYmEoMCwwLDAsMCk7ZGlzcGxheTppbmxpbmUtYmxvY2s7Zm9udC13ZWlnaHQ6NDAwO3RleHQtYWxpZ246Y2VudGVyO3VzZXItc2VsZWN0Om5vbmU7dmVydGljYWwtYWxpZ246bWlkZGxlO3RleHQtdHJhbnNmb3JtOm5vbmU7b3ZlcmZsb3c6dmlzaWJsZTttYXJnaW46MH0uc2Vjb25kYXJ5LWJ1dHRvbntiYWNrZ3JvdW5kLWNvbG9yOiNmM2Y0ZjY7Ym9yZGVyLWNvbG9yOiNmM2Y0ZjY7Y29sb3I6IzU2NWQ3Yn0uYnRuLXh4LXNte2ZvbnQtc2l6ZTouNzVyZW07cGFkZGluZzouMjVyZW0gLjc1cmVtfS5mb3JtLWFjdGlvbi1pY29uLGEuZWRpdC1zcHJlYWQsYS5kZWxldGUtc3ByZWFke2NvbG9yOiM1NjVkN2I7Zm9udC1zaXplOjE2cHg7bWFyZ2luLWxlZnQ6MTJweDt0ZXh0LWRlY29yYXRpb246bm9uZTtjdXJzb3I6cG9pbnRlcjtiYWNrZ3JvdW5kLWNvbG9yOnJnYmEoMCwwLDAsMCkgIWltcG9ydGFudH1AbWVkaWEgcHJpbnR7LmZvcm0tYWN0aW9uLWljb24sYS5lZGl0LXNwcmVhZCxhLmRlbGV0ZS1zcHJlYWR7ZGlzcGxheTpub25lfX0uZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIC5mb3JtLWFjdGlvbi1pY29uLC5kb2N1bWVudC1wcmV2aWV3LXdyYXBwZXIgYS5lZGl0LXNwcmVhZCwuZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIGEuZGVsZXRlLXNwcmVhZCwuZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIC5lZGl0LXNwcmVhZHtkaXNwbGF5Om5vbmV9QG1lZGlhIHByaW50ey5lZGl0LXNwcmVhZHtkaXNwbGF5Om5vbmV9fS5vdGhlci1maWVsZC1uYW1le2JhY2tncm91bmQ6I2U1ZWRmYiAwJSAwJSBuby1yZXBlYXQgcGFkZGluZy1ib3g7Ym9yZGVyLXJhZGl1czo0cHg7cGFkZGluZzo1cHggMTBweDt3aWR0aDphdXRvO2ZvbnQtc2l6ZToxMnB4O2FsaWduLWl0ZW1zOmNlbnRlcjtkaXNwbGF5OmlubGluZS1ibG9ja30uZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVye2JvcmRlcjoxcHggc29saWQgI2NmZDFkOTtib3JkZXItcmFkaXVzOjRweDtwYWRkaW5nLWJvdHRvbTowfS5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxle3dpZHRoOjEwMCU7Ym9yZGVyOjA7Ym9yZGVyLXJhZGl1czo0cHh9LmdlbmVyYXRlZC1maWVsZCAudGFibGUtZmllbGQtdGFibGUtd3JhcHBlciAudGFibGUtZmllbGQtdGFibGUgdGhlYWQgdHIgdGh7cGFkZGluZzoxNHB4O2JvcmRlcjowO3RleHQtYWxpZ246bGVmdDtib3JkZXItYm90dG9tOjFweCBzb2xpZCAjY2ZkMWQ5fS5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRoZWFkIHRyIHRoOm5vdCg6bGFzdC1jaGlsZCl7Ym9yZGVyLXJpZ2h0OjFweCBzb2xpZCAjZjNmNGY2fS5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRye2JvcmRlcjowfS5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRke2JvcmRlcjowfS5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRkIC50YWJsZS1maWVsZC1jZWxsLWRhdGF7YmFja2dyb3VuZDojZjNmNGY2IDAlIDAlIG5vLXJlcGVhdCBwYWRkaW5nLWJveDtib3JkZXItcmFkaXVzOjRweDtwYWRkaW5nOjVweCAxMHB4O21hcmdpbjo0cHg7d2lkdGg6YXV0bztmb250LXNpemU6MTJweDthbGlnbi1pdGVtczpjZW50ZXI7ZGlzcGxheTppbmxpbmUtYmxvY2t9QG1lZGlhIHByaW50ey5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRkIC50YWJsZS1maWVsZC1jZWxsLWRhdGF7YmFja2dyb3VuZDpyZ2JhKDAsMCwwLDApfX0uZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC10YWJsZSB0Ym9keSB0ciB0ZDpub3QoOmxhc3QtY2hpbGQpe2JvcmRlci1yaWdodDoxcHggc29saWQgI2YzZjRmNn0uZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC10YWJsZSB0Ym9keSB0cjpub3QoOmxhc3QtY2hpbGQpIHRke2JvcmRlci1ib3R0b206MXB4IHNvbGlkICNmM2Y0ZjZ9LmdlbmVyYXRlZC1maWVsZC5vdGhlci1maWVsZC1uYW1le2JhY2tncm91bmQ6I2YzZjRmNiAwJSAwJSBuby1yZXBlYXQgcGFkZGluZy1ib3g7Ym9yZGVyLXJhZGl1czo0cHg7cGFkZGluZzo1cHggMTBweDtmb250LXNpemU6MTJweDthbGlnbi1pdGVtczpjZW50ZXJ9LmdlbmVyYXRlZC1maWVsZC5vdGhlci1maWVsZC1uYW1lLmZ1bGwtd2lkdGgtZmllbGQsLmdlbmVyYXRlZC1maWVsZC5vdGhlci1maWVsZC1uYW1lW2RhdGEtZmllbGQtbmFtZT0ic3ByZWFkcy5nZW5lcmFsLmFsbFNwcmVhZHMiXSwuZ2VuZXJhdGVkLWZpZWxkLm90aGVyLWZpZWxkLW5hbWVbZGF0YS1maWVsZC1uYW1lPSJzcHJlYWRzLmdlbmVyYWwuYm9ycm93ZXJTcHJlYWRzIl0sLmdlbmVyYXRlZC1maWVsZC5vdGhlci1maWVsZC1uYW1lW2RhdGEtZmllbGQtbmFtZT0ic3ByZWFkcy5nZW5lcmFsLmd1YXJhbnRvclNwcmVhZHMiXXt3aWR0aDo5OC4yJX1AbWVkaWEgcHJpbnR7LmdlbmVyYXRlZC1maWVsZC5vdGhlci1maWVsZC1uYW1le2JhY2tncm91bmQ6cmdiYSgwLDAsMCwwKX19LmdlbmVyYXRlZC1maWVsZCAuY3VzdG9tLWZpZWxkLXRhYmxlLXdyYXBwZXJ7YmFja2dyb3VuZC1jb2xvcjojZmZmfS5mbGV4aS1mb3JtLXJlY29yZC1jb250YWluZXJ7YmFja2dyb3VuZDojZmZmIDAlIDAlIG5vLXJlcGVhdCBwYWRkaW5nLWJveDtib3JkZXI6MXB4IHNvbGlkICNjZmQxZDl9LmZsZXhpLWZvcm0tcmVjb3JkLWNvbnRhaW5lciAuZmxleGktZm9ybS1yZWNvcmQtaGVhZGVye3RleHQtYWxpZ246bGVmdDtmb250LXdlaWdodDpib2xkO2ZvbnQtc2l6ZToxOHB4O2xldHRlci1zcGFjaW5nOjBweDtjb2xvcjojMGYxOTQzO3BhZGRpbmc6MTJweDtib3JkZXItYm90dG9tOjFweCBzb2xpZCAjZGZlNmVmfS5mbGV4aS1mb3JtLXJlY29yZC1jb250YWluZXIgLmZsZXhpLWZvcm0tcmVjb3JkLWhlYWRlciAuZmxleGktZm9ybS1lZGl0e2Zsb2F0OnJpZ2h0O21hcmdpbi1yaWdodDoxNnB4fS5mbGV4aS1mb3JtLXJlY29yZC1jb250YWluZXIgLmZsZXhpLWZvcm0tcmVjb3JkLWhlYWRlciAuZmxleGktZm9ybS1kZWxldGV7ZmxvYXQ6cmlnaHR9LmZsZXhpLWZvcm0tcmVjb3JkLWNvbnRhaW5lciAuZmxleGktZm9ybS1yZWNvcmQtc2VjdGlvbnMtd3JhcHBlcnttYXJnaW46MCAxMCU7Ym9yZGVyLWxlZnQ6MXB4IHNvbGlkICNkZmU2ZWY7Ym9yZGVyLXJpZ2h0OjFweCBzb2xpZCAjZGZlNmVmfS5mbGV4aS1mb3JtLXJlY29yZC1jb250YWluZXIgLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb25zLXdyYXBwZXIgLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb24gLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb24taGVhZGVye2JhY2tncm91bmQ6I2YyZjNmNSAwJSAwJSBuby1yZXBlYXQgcGFkZGluZy1ib3g7Y29sb3I6IzBmMTk0MztwYWRkaW5nOjlweCA0NnB4IDEzcHggMjBweDtmb250LXdlaWdodDptZWRpdW07Zm9udC1zaXplOjE2cHh9LmZsZXhpLWZvcm0tcmVjb3JkLWNvbnRhaW5lciAuZmxleGktZm9ybS1yZWNvcmQtc2VjdGlvbnMtd3JhcHBlciAuZmxleGktZm9ybS1yZWNvcmQtc2VjdGlvbiAuZmxleGktZm9ybS1yZWNvcmQtc2VjdGlvbi1maWVsZHN7cGFkZGluZzoxNXB4IDQ2cHggMCAyMHB4O2ZvbnQtd2VpZ2h0Om1lZGl1bTtmb250LXNpemU6MTRweDtjb2xvcjojMGYxOTQzfS5mbGV4aS1mb3JtLXJlY29yZC1jb250YWluZXIgLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb25zLXdyYXBwZXIgLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb24gLmZsZXhpLWZvcm0tcmVjb3JkLXNlY3Rpb24tZmllbGRzIC5mbGV4aS1mb3JtLXJlY29yZC1zZWN0aW9uLWZpZWxke3BhZGRpbmctYm90dG9tOjIwcHh9LmV4cG9ydC13cmFwcGVyIC5mbGV4aS1mb3JtLXJlY29yZC1oZWFkZXIgLmZsZXhpLWZvcm0tZWRpdCwuZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIC5mbGV4aS1mb3JtLXJlY29yZC1oZWFkZXIgLmZsZXhpLWZvcm0tZWRpdHtkaXNwbGF5Om5vbmV9LmV4cG9ydC13cmFwcGVyIC5mbGV4aS1mb3JtLXJlY29yZC1oZWFkZXIgLmZsZXhpLWZvcm0tZGVsZXRlLC5kb2N1bWVudC1wcmV2aWV3LXdyYXBwZXIgLmZsZXhpLWZvcm0tcmVjb3JkLWhlYWRlciAuZmxleGktZm9ybS1kZWxldGV7ZGlzcGxheTpub25lfS5keW5hbWljLWNvbXBvbmVudHMtd3JhcHBlciAuZHluYW1pYy1jb21wb25lbnQtaGVhZGVye2ZvbnQtc2l6ZToyMnB4O2ZvbnQtd2VpZ2h0OmJvbGQ7dGV4dC1kZWNvcmF0aW9uOnVuZGVybGluZX0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmR5bmFtaWMtY29tcG9uZW50LXNlY3Rpb24taGVhZGVye2ZvbnQtc2l6ZToyMHB4O2ZvbnQtd2VpZ2h0OmJvbGQ7dGV4dC1kZWNvcmF0aW9uOnVuZGVybGluZX0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmR5bmFtaWMtY29tcG9uZW50LXN1Yi1oZWFkZXJ7Zm9udC1zaXplOjE4cHg7Zm9udC13ZWlnaHQ6Ym9sZH0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmR5bmFtaWMtY29tcG9uZW50LXN1Yi1oZWFkZXItMntmb250LXNpemU6MTZweDtmb250LXdlaWdodDpib2xkfS5keW5hbWljLWNvbXBvbmVudHMtd3JhcHBlciAuZWFjaC1keW5hbWljLWNvbXBvbmVudC13cmFwcGVye2Rpc3BsYXk6ZmxleDtmbGV4LWRpcmVjdGlvbjpjb2x1bW47cm93LWdhcDoxMHB4fS5keW5hbWljLWNvbXBvbmVudHMtd3JhcHBlciAuZWFjaC1keW5hbWljLWNvbXBvbmVudC13cmFwcGVyIC5sYWJlbC12YWx1ZS13cmFwcGVye2Rpc3BsYXk6ZmxleDtmbGV4LWRpcmVjdGlvbjpyb3c7ZmxleC13cmFwOndyYXA7cm93LWdhcDoxMHB4fS5keW5hbWljLWNvbXBvbmVudHMtd3JhcHBlciAuZWFjaC1keW5hbWljLWNvbXBvbmVudC13cmFwcGVyIC5sYWJlbC12YWx1ZS13cmFwcGVyIC5lYWNoLWNvbXBvbmVudC1maWVsZHt3aWR0aDozMy4zJX0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmVhY2gtZHluYW1pYy1jb21wb25lbnQtd3JhcHBlciAubGFiZWwtdmFsdWUtd3JhcHBlciAuZWFjaC1jb21wb25lbnQtZmllbGQuZnVsbC13aWR0aC1maWVsZHt3aWR0aDoxMDAlfS5keW5hbWljLWNvbXBvbmVudHMtd3JhcHBlciAuZWFjaC1keW5hbWljLWNvbXBvbmVudC13cmFwcGVyIC5sYWJlbC12YWx1ZS13cmFwcGVyIC5lYWNoLWNvbXBvbmVudC1maWVsZC5oYWxmLXdpZHRoLWZpZWxke3dpZHRoOjUwJX0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmVhY2gtZHluYW1pYy1jb21wb25lbnQtd3JhcHBlciAubGFiZWwtdmFsdWUtd3JhcHBlciAuZWFjaC1jb21wb25lbnQtZmllbGQgLmVhY2gtY29tcG9uZW50LWZpZWxkLWxhYmVse2ZvbnQtc2l6ZToxNHB4O2ZvbnQtd2VpZ2h0OmJvbGR9LmR5bmFtaWMtY29tcG9uZW50cy13cmFwcGVyIC5lYWNoLWR5bmFtaWMtY29tcG9uZW50LXdyYXBwZXIgLmxhYmVsLXZhbHVlLXdyYXBwZXIgLmVhY2gtY29tcG9uZW50LWZpZWxkIC5lYWNoLWNvbXBvbmVudC1maWVsZC12YWx1ZXtmb250LXNpemU6MTRweH0uZHluYW1pYy1jb21wb25lbnRzLXdyYXBwZXIgLmVhY2gtZHluYW1pYy1jb21wb25lbnQtd3JhcHBlciAuZHluYW1pYy1zdWItY29tcG9uZW50LXdyYXBwZXIgLmR5bmFtaWMtc3ViLWNvbXBvbmVudC1ib2R5e2Rpc3BsYXk6ZmxleDtmbGV4LWRpcmVjdGlvbjpjb2x1bW47cm93LWdhcDoxMHB4fS5leHBvcnQtd3JhcHBlciAuZm9ybS1hY3Rpb24taWNvbiwuZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIC5mb3JtLWFjdGlvbi1pY29ue2Rpc3BsYXk6bm9uZX0uZXhwb3J0LXdyYXBwZXIgLmVkaXQtc3ByZWFkLC5kb2N1bWVudC1wcmV2aWV3LXdyYXBwZXIgLmVkaXQtc3ByZWFke2Rpc3BsYXk6bm9uZX0uZXhwb3J0LXdyYXBwZXIgLmdlbmVyYXRlZC1maWVsZCAudGFibGUtZmllbGQtdGFibGUtd3JhcHBlciAudGFibGUtZmllbGQtdGFibGUgdGJvZHkgdHIgdGQsLmRvY3VtZW50LXByZXZpZXctd3JhcHBlciAuZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC10YWJsZSB0Ym9keSB0ciB0ZHtib3JkZXI6MH0uZXhwb3J0LXdyYXBwZXIgLmdlbmVyYXRlZC1maWVsZCAudGFibGUtZmllbGQtdGFibGUtd3JhcHBlciAudGFibGUtZmllbGQtdGFibGUgdGJvZHkgdHIgdGQgLnRhYmxlLWZpZWxkLWNlbGwtZGF0YSwuZG9jdW1lbnQtcHJldmlldy13cmFwcGVyIC5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRkIC50YWJsZS1maWVsZC1jZWxsLWRhdGF7YmFja2dyb3VuZDpyZ2JhKDAsMCwwLDApfS5leHBvcnQtd3JhcHBlciAuZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC10YWJsZSB0Ym9keSB0ciB0ZDpub3QoOmxhc3QtY2hpbGQpLC5kb2N1bWVudC1wcmV2aWV3LXdyYXBwZXIgLmdlbmVyYXRlZC1maWVsZCAudGFibGUtZmllbGQtdGFibGUtd3JhcHBlciAudGFibGUtZmllbGQtdGFibGUgdGJvZHkgdHIgdGQ6bm90KDpsYXN0LWNoaWxkKXtib3JkZXItcmlnaHQ6MXB4IHNvbGlkICNmM2Y0ZjZ9LmV4cG9ydC13cmFwcGVyIC5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRkOm5vdCg6bGFzdC1jaGlsZCksLmV4cG9ydC13cmFwcGVyIC5nZW5lcmF0ZWQtZmllbGQgLnRhYmxlLWZpZWxkLXRhYmxlLXdyYXBwZXIgLnRhYmxlLWZpZWxkLXRhYmxlIHRib2R5IHRyIHRkOmxhc3QtY2hpbGQsLmRvY3VtZW50LXByZXZpZXctd3JhcHBlciAuZ2VuZXJhdGVkLWZpZWxkIC50YWJsZS1maWVsZC10YWJsZS13cmFwcGVyIC50YWJsZS1maWVsZC10YWJsZSB0Ym9keSB0ciB0ZDpub3QoOmxhc3QtY2hpbGQpLC5kb2N1bWVudC1wcmV2aWV3LXdyYXBwZXIgLmdlbmVyYXRlZC1maWVsZCAudGFibGUtZmllbGQtdGFibGUtd3JhcHBlciAudGFibGUtZmllbGQtdGFibGUgdGJvZHkgdHIgdGQ6bGFzdC1jaGlsZHtib3JkZXItYm90dG9tOjFweCBzb2xpZCAjZjNmNGY2fS5leHBvcnQtd3JhcHBlciAuZ2VuZXJhdGVkLWZpZWxkLm90aGVyLWZpZWxkLW5hbWUsLmRvY3VtZW50LXByZXZpZXctd3JhcHBlciAuZ2VuZXJhdGVkLWZpZWxkLm90aGVyLWZpZWxkLW5hbWV7YmFja2dyb3VuZDpyZ2JhKDAsMCwwLDApfQ==%22,%22formHeaderContent%22:%22PHA+PGltZyBzcmM9Imh0dHBzOi8vbG9zdGVzdC5jeW5jc29mdHdhcmUuY29tL2RlZmF1bHQvbG9nby5wbmciIHdpZHRoPSIxMjUiIGhlaWdodD0iODAiIGFsdD0iIiBzdHlsZT0iZGlzcGxheTogYmxvY2s7IG1hcmdpbi1sZWZ0OiBhdXRvOyBtYXJnaW4tcmlnaHQ6IGF1dG87Ij48L3A+CjxwIHN0eWxlPSJ0ZXh0LWFsaWduOiBjZW50ZXI7Ij48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMHB0OyI+VGVtcGxhdGUgTmFtZTogPHNwYW4gY2xhc3M9Im90aGVyLWZpZWxkLW5hbWUgbWNlTm9uRWRpdGFibGUgIiBkYXRhLWZpZWxkLW5hbWU9ImZvcm1zTWFuYWdlci5mb3JtVGVtcGxhdGUuZ2VuZXJhbC5mb3JtVGVtcGxhdGVOYW1lIj4gRm9ybSBUZW1wbGF0ZSBOYW1lIDwvc3Bhbj4mbmJzcDs8L3NwYW4+PC9wPgo8cCBzdHlsZT0idGV4dC1hbGlnbjogY2VudGVyOyI+PHNwYW4gY2xhc3M9Im90aGVyLWZpZWxkLW5hbWUgbWNlTm9uRWRpdGFibGUgIiBkYXRhLWZpZWxkLW5hbWU9ImZvcm1zTWFuYWdlci5mb3JtVGVtcGxhdGUuZ2VuZXJhbC5mb3JtVGVtcGxhdGVOYW1lIj4gRm9ybSBUZW1wbGF0ZSBOYW1lIDwvc3Bhbj4mbmJzcDs8L3A+CjxwIHN0eWxlPSJ0ZXh0LWFsaWduOiBjZW50ZXI7Ij48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMHB0OyI+PC9zcGFuPjwvcD4=%22,%22formFooterContent%22:%22PGRpdiBzdHlsZT0id2lkdGg6IDEwMCU7Ij4KPHAgc3R5bGU9InRleHQtYWxpZ246IGNlbnRlcjsiPjxzcGFuIHN0eWxlPSJmb250LXNpemU6IDEwcHQ7Ij5DPHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogMTJwdDsiPnJlYXRlZCBCeTogPC9zcGFuPjwvc3Bhbj48c3BhbiBjbGFzcz0ib3RoZXItZmllbGQtbmFtZSBtY2VOb25FZGl0YWJsZSAiIGRhdGEtZmllbGQtbmFtZT0iZm9ybXNNYW5hZ2VyLmZvcm1Eb2N1bWVudC5nZW5lcmFsLmZvcm1Eb2N1bWVudENyZWF0ZWRCeSI+IEZvcm0gRG9jdW1lbnQgQ3JlYXRlZCBCeSA8L3NwYW4+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogMTJwdDsiPiZuYnNwOyAmbmJzcDsgfCZuYnNwOyAmbmJzcDs8L3NwYW4+PHNwYW4gY2xhc3M9Im90aGVyLWZpZWxkLW5hbWUgbWNlTm9uRWRpdGFibGUiPiA8c3BhbiBjbGFzcz0icGFnZU51bWJlciI+UGFnZSBOdW1iZXIgPC9zcGFuPi88c3BhbiBjbGFzcz0idG90YWxQYWdlcyI+PC9zcGFuPiA8L3NwYW4+PC9wPgo8cCBzdHlsZT0idGV4dC1hbGlnbjogY2VudGVyOyI+PHNwYW4gc3R5bGU9ImZvbnQtc2l6ZTogMTBwdDsiPkN5bmMgSW5jLiB8IDQ0MzIzNDU0MzIgfCAzNTA1IEVhc3QgRnJvbnRhZ2UgUm9hZCBTdWl0ZSAxNjAxIHwmbmJzcDs8L3NwYW4+PGEgaHJlZj0iaHR0cHM6Ly93d3cuY3luY3NvZnR3YXJlLmNvbSIgc3R5bGU9ImZvbnQtc2l6ZTogMTBwdDsiPnd3dy5jeW5jc29mdHdhcmUuY29tPC9hPjxicj48c3BhbiBzdHlsZT0iZm9udC1zaXplOiAxMHB0OyI+PC9zcGFuPjwvcD4KPHAgc3R5bGU9ImZvbnQtc2l6ZTogMTBwdDsgbWFyZ2luOiAxMnB4OyB0ZXh0LWFsaWduOiByaWdodDsiPjwvcD4KPHAgc3R5bGU9ImZvbnQtc2l6ZTogMTBwdDsgbWFyZ2luOiAxMnB4OyB0ZXh0LWFsaWduOiByaWdodDsiPiZuYnNwOzwvcD4KPHAgc3R5bGU9InRleHQtYWxpZ246IGNlbnRlcjsiPiZuYnNwOzwvcD4KPC9kaXY+%22,%22formHideHeader%22:false,%22formHideFooter%22:false,%22domainName%22:%22loans%22,%22domainId%22:%22XYZ0000002519%22,%22createdAt%22:%222024-03-14T07:04:07.481Z%22,%22createdBy%22:85,%22modifiedAt%22:%222024-03-14T07:04:07.481Z%22,%22modifiedBy%22:85,%22createdByName%22:%22Robin%20B%22,%22modifiedByName%22:%22Robin%20B%22%7D%7D">Robin B</span><span style="font-size: 12pt;">&nbsp; &nbsp; |&nbsp; &nbsp;</span><span class="other-field-name mceNonEditable"> <span class="pageNumber">Page Number </span>/<span class="totalPages"></span> </span></p>
<p style="text-align: center;"><span style="font-size: 10pt;">Cync Inc. | 4432345432 | 3505 East Frontage Road Suite 1601 |&nbsp;</span><a href="https://www.cyncsoftware.com" style="font-size: 10pt;">www.cyncsoftware.com</a><br><span style="font-size: 10pt;"></span></p>
<p style="font-size: 10pt; margin: 12px; text-align: right;"></p>
<p style="font-size: 10pt; margin: 12px; text-align: right;">&nbsp;</p>
<p style="text-align: center;">&nbsp;</p>
</div>
`

const footer = `
<div style="width: 100%;" style="font-size: 10pt; ">
<p style="text-align: right;">
   <span style="font-size: 10pt;">Created By: </span>
      <span class="other-field-name mceNonEditable generated-field" style="font-size: 10pt; data-field-name="formsManager.formDocument.general.formDocumentCreatedBy">Robin B</span>
   <span style="font-size: 12pt;">&nbsp; &nbsp; |&nbsp; &nbsp;</span>
   <span class="other-field-name mceNonEditable" style="font-size: 10pt;"> 
      <span class="pageNumber">Page Number </span>/<span class="totalPages"></span> 
   </span>
</p>
<p style="text-align: center;"><span style="font-size: 10pt;">Cync Inc. | 4432345432 | 3505 East Frontage Road Suite 1601 |&nbsp;</span><a href="https://www.cyncsoftware.com" style="font-size: 10pt;">www.cyncsoftware.com</a><br><span style="font-size: 10pt;"></span></p>
<p style="font-size: 10pt; margin: 12px; text-align: right;"></p>
<p style="font-size: 10pt; margin: 12px; text-align: right;">&nbsp;</p>
<p style="text-align: center;">&nbsp;</p>
</div>
`;

const content = Buffer.from(jsonSample.baseforpup, "base64").toString("utf8")

const HTML_SAMPLE = `
<!doctype html>
<html>

<head>
   <meta name="viewport" content="width=device-width">
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   ${EDITOR_STYLES}

   <style>

</style>
</head>

<body>

<p></p>
<p><span style="font-family: arial, helvetica, sans-serif;"><span style="text-decoration: underline;">Arial font check</span> - Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsu</span><span style="font-family: arial, helvetica, sans-serif;"></span><span style="font-family: tahoma, arial, helvetica, sans-serif;"></span></p>
<p><span style="font-family: tahoma, arial, helvetica, sans-serif;"><span style="font-family: 'times new roman', times, serif;"><span style="text-decoration: underline;">Times new roman check</span> - <strong>Lorem Ipsum</strong>&nbsp;is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsu</span></span></p>
<p><span style="font-family: tahoma, arial, helvetica, sans-serif;"><span style="text-decoration: underline;">Tahoma font check</span> - Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsu</span></p>
<p><span style="font-family: terminal, monaco, monospace;"><span style="text-decoration: underline;">Terminal font check</span> - Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsu</span></p>


</body>

</html>
`

const html_samp_content = `
<p><span style=\"text-decoration: underline;\"><strong>Exceptions list:</strong></span></p>\n<p></p>\n<div id=\"exception.general.exceptionsList-0\" class=\"mceNonEditable generated-field\" data-field-name=\"exception.general.exceptionsList\" data-field-details=\"%7B%22elmId%22:%22exception.general.exceptionsList-0%22,%22hideEmptyTable%22:false,%22arrangedFieldNames%22:%5B%22exception.general.exceptionsList.type%22,%22exception.general.exceptionsList.exceptionSubtype%22,%22exception.general.exceptionsList.loanName%22,%22exception.general.exceptionsList.description%22,%22exception.general.exceptionsList.severity%22,%22exception.general.exceptionsList.status%22%5D,%22sortBy%22:%7B%22name%22:%22exception.general.exceptionsList.exceptionSubtype%22,%22order%22:%22desc%22%7D,%22groupBy%22:%5B%22exception.general.exceptionsList.type%22%5D%7D\">\n        <div class=\"table-field-table-wrapper\">\n            <table class=\"table-field-table\" border=\"0\">\n<thead>\n<tr>\n<th align=\"center\">Type</th>\n<th align=\"center\">Exception Name</th>\n<th align=\"center\">Loan Name</th>\n<th align=\"center\">Comments</th>\n<th align=\"center\">Severity Level</th>\n<th align=\"center\">Status</th>\n</tr>\n</thead>\n\n            \n            \n            <tbody>\n                    <tr>\n                            <td><span class=\"table-field-cell-data\">other</span></td>\n                            <td><span class=\"table-field-cell-data\">test113</span></td>\n                            <td><span class=\"table-field-cell-data\">Test Approval flow - raghul</span></td>\n                            <td><span class=\"table-field-cell-data\"></span></td>\n                            <td><span class=\"table-field-cell-data\">Critical</span></td>\n                            <td><span class=\"table-field-cell-data\">Unmitigated</span></td>\n                    </tr>\n                    <tr>\n                            <td><span class=\"table-field-cell-data\">Policy</span></td>\n                            <td><span class=\"table-field-cell-data\">sub1</span></td>\n                            <td><span class=\"table-field-cell-data\">Test Approval flow - raghul</span></td>\n                            <td><span class=\"table-field-cell-data\"></span></td>\n                            <td><span class=\"table-field-cell-data\">Non-Critical</span></td>\n                            <td><span class=\"table-field-cell-data\">Unmitigated</span></td>\n                    </tr>\n                    <tr>\n                            <td><span class=\"table-field-cell-data\"></span></td>\n                            <td><span class=\"table-field-cell-data\">other1</span></td>\n                            <td><span class=\"table-field-cell-data\">Test Approval flow - raghul</span></td>\n                            <td><span class=\"table-field-cell-data\"></span></td>\n                            <td><span class=\"table-field-cell-data\">Non-Critical</span></td>\n                            <td><span class=\"table-field-cell-data\">Unmitigated</span></td>\n                    </tr>\n                    <tr>\n                            <td><span class=\"table-field-cell-data\"></span></td>\n                            <td><span class=\"table-field-cell-data\">MannaEx2</span></td>\n                            <td><span class=\"table-field-cell-data\">Test Approval flow - raghul</span></td>\n                            <td><span class=\"table-field-cell-data\"></span></td>\n                            <td><span class=\"table-field-cell-data\">Non-Critical</span></td>\n                            <td><span class=\"table-field-cell-data\">Unmitigated</span></td>\n                    </tr>\n                    <tr>\n                            <td><span class=\"table-field-cell-data\">Testing Exception</span></td>\n                            <td><span class=\"table-field-cell-data\">other - Test</span></td>\n                            <td><span class=\"table-field-cell-data\">Test Approval flow - raghul</span></td>\n                            <td><span class=\"table-field-cell-data\"></span></td>\n                            <td><span class=\"table-field-cell-data\">Critical</span></td>\n                            <td><span class=\"table-field-cell-data\">Unmitigated</span></td>\n                    </tr>\n            </tbody>\n            </table>\n        </div>\n    </div>\n<p>&nbsp;</p>\n<p style=\"text-align: left;\"><span style=\"text-decoration: underline; font-size: 14pt;\"><strong><span style=\"color: rgb(0, 0, 0); text-decoration: underline;\">Template Details</span></strong></span><span style=\"text-decoration: underline; font-size: 24pt;\"><strong><span style=\"color: rgb(0, 0, 0); text-decoration: underline;\"></span></strong></span></p>\n<table border=\"1\" class=\"editor-table\" style=\"border-collapse: collapse; width: 100%;\"><colgroup><col style=\"width: 25.0181%;\"><col style=\"width: 24.9458%;\"><col style=\"width: 25.0904%;\"><col style=\"width: 24.9458%;\"></colgroup>\n<tbody>\n<tr>\n<td style=\"text-align: center;\"><span style=\"font-size: 12pt;\">&nbsp; Loan Name</span></td>\n<td style=\"text-align: center;\"><span style=\"font-size: 12pt;\">loan Number</span></td>\n<td style=\"text-align: center;\"><span style=\"font-size: 12pt;\">Barrower Name</span></td>\n<td style=\"text-align: center;\"><span style=\"font-size: 12pt;\">Phone Number</span></td>\n</tr>\n<tr>\n<td style=\"text-align: center;\"><span class=\"other-field-name mceNonEditable generated-field\" data-field-name=\"loan.transaction.general.loanNumber\"></span><span style=\"font-size: 12pt;\">&nbsp;</span></td>\n<td style=\"text-align: center;\"><span class=\"other-field-name mceNonEditable generated-field\" data-field-name=\"loan.transaction.general.loanNumber\"></span><span style=\"font-size: 12pt;\">&nbsp;</span></td>\n<td style=\"text-align: center;\"><span class=\"other-field-name mceNonEditable generated-field\" data-field-name=\"riskRating.general.borrowerAllRiskRatingDetails\"></span><span style=\"font-size: 12pt;\">&nbsp;</span></td>\n<td style=\"text-align: center;\"><span class=\"other-field-name mceNonEditable generated-field\" data-field-name=\"relationship.borrower.phoneNumber\"></span><span style=\"font-size: 12pt;\">&nbsp;</span></td>\n</tr>\n</tbody>\n</table>
`

const HTMLSampleDev = `
<!doctype html>
<html>
    <head>
    <meta name="viewport" content="width=device-width">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    ${EDITOR_STYLES}
    </head>
    <body class="export-wrapper">
    <div class="newDiv">
    ${header}
    ${html_samp_content}
    </div>
    </body>
</html>

`

const htmlFailEle = `
<!doctype html>
      <html>
          <head>
          <meta name="viewport" content="width=device-width">
          <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
          
<link href="https://fonts.cdnfonts.com/css/roboto" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/andale-mono" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/arial" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/antiqua-2" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/sans-comic-sans" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/just-another-courier" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/georgia" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/helvetica-neue-55" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/impact" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/symbol" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/tahoma" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/terminal" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/times-new-roman" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/trebuchet-ms-2" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/verdana" rel="stylesheet">
<link href="https://fonts.cdnfonts.com/css/monaco" rel="stylesheet">

          <style>
          body.mce-content-body,body.print-body,.export-wrapper,.document-preview-wrapper{font-family:Roboto,Helvetica,Verdana,sans-serif !important;font-size:14pt !important;height:100%}body.mce-content-body .editor-table tr td,body.print-body .editor-table tr td,.export-wrapper .editor-table tr td,.document-preview-wrapper .editor-table tr td{height:25px}.table-field-table-wrapper{border:1px solid #cfd1d9;border-radius:4px;padding-bottom:15px}.table-field-table-wrapper .edit-table-field,.table-field-table-wrapper .delete-table-field{color:#6f758e;padding:5px 0;margin-right:.5em;text-decoration:none}.table-field-table-wrapper .table-field-name{background:#e5f7e9 0% 0% no-repeat padding-box;padding:5px 10px;width:auto;display:inline-flex;margin:11px;border-radius:4px;align-items:center}.table-field-table-wrapper .table-field-name .tooltip-container{position:relative;margin-left:8px;cursor:pointer}.table-field-table-wrapper .table-field-name .tooltip-text{visibility:hidden;width:150px;background-color:#0f1943;color:#fff;text-align:center;padding:8px 6px;border-radius:4px;position:absolute;z-index:1;top:160%;left:-70px;opacity:0;transition:opacity .3s}.table-field-table-wrapper .table-field-name .tooltip-text::after{content:"";position:absolute;top:-9px;left:50%;margin-left:-5px;border-width:5px;border-style:solid;border-color:rgba(0,0,0,0) rgba(0,0,0,0) #0f1943 rgba(0,0,0,0)}.table-field-table-wrapper .table-field-name .tooltip-container:hover .tooltip-text{visibility:visible;opacity:1}.table-field-table-wrapper .table-field-table{width:100%;border:0}.table-field-table-wrapper .table-field-table thead tr th{border:0;border-right:1px solid #cfd1d9;padding-left:14px;text-align:left}.deleted-spread-content{position:relative;background:rgba(0,0,0,0);text-align:center;width:100%;padding:20px 0;margin-bottom:20px}.deleted-spread-content .deleted-spread-content-title{font-size:.875rem;padding-bottom:10px}.primary-button,.secondary-button{cursor:pointer;background-color:#0055d5;border-color:#0055d5;padding:.44rem 1.25rem;font-size:.875rem;border-radius:.2rem;color:#fff;border:1px solid rgba(0,0,0,0);display:inline-block;font-weight:400;text-align:center;user-select:none;vertical-align:middle;text-transform:none;overflow:visible;margin:0}.secondary-button{background-color:#f3f4f6;border-color:#f3f4f6;color:#565d7b}.btn-xx-sm{font-size:.75rem;padding:.25rem .75rem}.form-action-icon,a.edit-spread,a.delete-spread{color:#565d7b;font-size:16px;margin-left:12px;text-decoration:none;cursor:pointer;background-color:rgba(0,0,0,0) !important}@media print{.form-action-icon,a.edit-spread,a.delete-spread{display:none}}.document-preview-wrapper .form-action-icon,.document-preview-wrapper a.edit-spread,.document-preview-wrapper a.delete-spread,.document-preview-wrapper .edit-spread{display:none}@media print{.edit-spread{display:none}}.other-field-name{background:#e5edfb 0% 0% no-repeat padding-box;border-radius:4px;padding:5px 10px;width:auto;align-items:center}.generated-field .table-field-table-wrapper{border:0;border-radius:0;padding-bottom:0}.generated-field .table-field-table-wrapper .table-field-table{width:100%;border:0;border-radius:4px;border:1px solid #cfd1d9}.generated-field .table-field-table-wrapper .table-field-table thead tr th{padding:14px;border:0;text-align:left;border-bottom:1px solid #cfd1d9}.generated-field .table-field-table-wrapper .table-field-table thead tr th:not(:last-child){border-right:1px solid #f3f4f6}.generated-field .table-field-table-wrapper .table-field-table tbody tr{border:0}.generated-field .table-field-table-wrapper .table-field-table tbody tr td{border:0}.generated-field .table-field-table-wrapper .table-field-table tbody tr td .table-field-cell-data{background:#f3f4f6 0% 0% no-repeat padding-box;border-radius:4px;padding:5px 10px;margin:4px;width:auto;font-size:12px;align-items:center;display:inline-block}@media print{.generated-field .table-field-table-wrapper .table-field-table tbody tr td .table-field-cell-data{background:rgba(0,0,0,0)}}.generated-field .table-field-table-wrapper .table-field-table tbody tr td:not(:last-child){border-right:1px solid #f3f4f6}.generated-field .table-field-table-wrapper .table-field-table tbody tr:not(:last-child) td{border-bottom:1px solid #f3f4f6}.generated-field.other-field-name{background:#f3f4f6 0% 0% no-repeat padding-box;border-radius:4px;padding:5px 10px;align-items:center;display:inline-block}.generated-field.other-field-name.full-width-field,.generated-field.other-field-name[data-field-name="spreads.general.allSpreads"],.generated-field.other-field-name[data-field-name="spreads.general.borrowerSpreads"],.generated-field.other-field-name[data-field-name="spreads.general.guarantorSpreads"]{width:98.2%}@media print{.generated-field.other-field-name{background:rgba(0,0,0,0)}}.generated-field .custom-field-table-wrapper{background-color:#fff}.comment-header-section-div{margin-left:24px;margin-top:24px;margin-bottom:12px;font-weight:bold}.comment-dot-separator{width:4px;height:4px;border-radius:50%;background-color:#000;margin:auto 8px}.comment-section-main-div{margin-left:24px}.comment-section-main-div .comment-section-div{display:flex;flex-direction:row;margin-top:12px}.comment-section-main-div .comment-section-div .comment-user-name-bubble{border:2px solid #cfd1d9;height:32px;width:32px;background-color:#e6e7ec;border-radius:50%;margin:auto;display:flex;align-items:center;justify-content:center}.comment-section-main-div .comment-section-div .comment-div{margin-left:8px;color:#0f1943}.comment-section-main-div .comment-section-div .comment-line-1{display:flex;flex-direction:row;font-size:12px}.comment-section-main-div .comment-section-div .comment-line-2{margin-top:4px;font-size:14px}.flexi-form-record-container{background:#fff 0% 0% no-repeat padding-box;border:1px solid #cfd1d9}.flexi-form-record-container .flexi-form-record-header{text-align:left;font-weight:bold;font-size:18px;letter-spacing:0px;color:#0f1943;padding:12px;border-bottom:1px solid #dfe6ef}.flexi-form-record-container .flexi-form-record-header .flexi-form-edit{float:right;margin-right:16px}.flexi-form-record-container .flexi-form-record-header .flexi-form-delete{float:right}.flexi-form-record-container .flexi-form-record-sections-wrapper{margin:0 10%;border-left:1px solid #dfe6ef;border-right:1px solid #dfe6ef}.flexi-form-record-container .flexi-form-record-sections-wrapper .flexi-form-record-section .flexi-form-record-section-header{background:#f2f3f5 0% 0% no-repeat padding-box;color:#0f1943;padding:9px 46px 13px 20px;font-weight:medium;font-size:16px}.flexi-form-record-container .flexi-form-record-sections-wrapper .flexi-form-record-section .flexi-form-record-section-fields{padding:15px 46px 0 20px;font-weight:medium;font-size:14px;color:#0f1943}.flexi-form-record-container .flexi-form-record-sections-wrapper .flexi-form-record-section .flexi-form-record-section-fields .flexi-form-record-section-field{padding-bottom:20px}.export-wrapper .flexi-form-record-header .flexi-form-edit,.document-preview-wrapper .flexi-form-record-header .flexi-form-edit{display:none}.export-wrapper .flexi-form-record-header .flexi-form-delete,.document-preview-wrapper .flexi-form-record-header .flexi-form-delete{display:none}.dynamic-components-wrapper .dynamic-component-header{font-size:22px;font-weight:bold;text-decoration:underline}.dynamic-components-wrapper .dynamic-component-section-header{font-size:20px;font-weight:bold;text-decoration:underline}.dynamic-components-wrapper .dynamic-component-sub-header{font-size:18px;font-weight:bold}.dynamic-components-wrapper .dynamic-component-sub-header-2{font-size:16px;font-weight:bold}.dynamic-components-wrapper .each-dynamic-component-wrapper{display:flex;flex-direction:column;row-gap:10px}.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper{display:flex;flex-direction:row;flex-wrap:wrap;row-gap:10px}.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper .each-component-field{width:33.3%}.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper .each-component-field.full-width-field{width:100%}.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper .each-component-field.half-width-field{width:50%}.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper .each-component-field .each-component-field-label{font-size:14px;font-weight:bold}.dynamic-components-wrapper .each-dynamic-component-wrapper .label-value-wrapper .each-component-field .each-component-field-value{font-size:14px}.dynamic-components-wrapper .each-dynamic-component-wrapper .dynamic-sub-component-wrapper .dynamic-sub-component-body{display:flex;flex-direction:column;row-gap:10px}.export-wrapper .form-action-icon,.document-preview-wrapper .form-action-icon{display:none}.export-wrapper .edit-spread,.document-preview-wrapper .edit-spread{display:none}.export-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td,.document-preview-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td{border:0}.export-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td .table-field-cell-data,.document-preview-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td .table-field-cell-data{background:rgba(0,0,0,0)}.export-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td:not(:last-child),.document-preview-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td:not(:last-child){border-right:1px solid #f3f4f6}.export-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td:not(:last-child),.export-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td:last-child,.document-preview-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td:not(:last-child),.document-preview-wrapper .generated-field .table-field-table-wrapper .table-field-table tbody tr td:last-child{border-bottom:1px solid #f3f4f6}.export-wrapper .generated-field.other-field-name,.document-preview-wrapper .generated-field.other-field-name{background:rgba(0,0,0,0)}
          </style>
          </head>
          <body class="export-wrapper">
          <div> <body><div><p>
            <img src="https://lostest.cyncsoftware.com/default/logo.png" width="125" height="80" alt="" style="display: block; margin-left: auto; margin-right: auto;">
        </p>
        </div></body></div>
              <body><div><div><div class="other-field-name full-width-field generated-field" data-field-name="loan.transaction.bbc"> <div class="bbc-wrapper dynamic-components-wrapper">  <div class="dynamic-component-header"> Test File Version </div> <div class="each-dynamic-component-wrapper"> <div class="label-value-wrapper">  <div class="each-component-field"> <div class="each-component-field-label"> Borrowing Base Certificate (BBC) </div> <div class="each-component-field-value"> No </div> </div>  <div class="each-component-field"> <div class="each-component-field-label"> BBC Frequency </div> <div class="each-component-field-value"> - </div> </div>  <div class="each-component-field"> <div class="each-component-field-label"> Collateral Field Exam </div> <div class="each-component-field-value"> - </div> </div>  <div class="each-component-field"> <div class="each-component-field-label"> Indicate Collateral Field Exam </div> <div class="each-component-field-value"> - </div> </div>  <div class="each-component-field"> <div class="each-component-field-label"> Other, Please Specify </div> <div class="each-component-field-value"> - </div> </div>  <div class="each-component-field"> <div class="each-component-field-label"> Account Type </div> <div class="each-component-field-value"> - </div> </div>  <div class="each-component-field"> <div class="each-component-field-label"> Direct Assignments of Contract </div> <div class="each-component-field-value"> - </div> </div>  <div class="each-component-field"> <div class="each-component-field-label"> Describe Contracts </div> <div class="each-component-field-value"> - </div> </div>  </div>  </div>  </div> </div></div></div></body>
          </body>
      </html>
`

const execute = async () => {

   try {


      const browser = await puppeteer.launch({
         headless: false,
         defaultViewport: null,
         // args: ['--disable-features=site-per-process']
      });
      const page = await browser.newPage();


      console.log("page created")
      // replace setContent with goto and give the url with options to wait``Until networkidl20
      // await page.goto(`data:text/html,${html}`, { waitUntil: 'networkidle0' }); 
      // await page.goto(`https://codepen.io/challenges/`, { waitUntil: 'networkidle0' }); 

      // best option is to use setconent with waitUntil than goto
      await page.setContent(HTMLSampleDev, { timeout: 0, waitUntil: 'networkidle0' });


      console.log("page content set")

      // const b64 = Buffer.from(HTMLSampleDev).toString('base64');
      // await page.goto(`data:text/html;base`64,${b64}`);

      await page.emulateMediaType('screen');
      const pdf = await page.pdf({
         path: 'result1234.pdf',
         margin: { top: '40px', right: '40px', bottom: '120px', left: '40px' },
         printBackground: true,
         format: 'Letter',
         displayHeaderFooter: true,
         headerTemplate: `
         <div></div>
      `,
         footerTemplate: footer

         // footerTemplate: `
         // <div style="text-align: center;">
         //     <span style="font-size: 12px;">
         //         Cync Inc | 4432345432 | 3505 East Frontage Road Suite 160 | https://cyncsoftware.com/
         //     </span>
         // </div>
         // <div style="margin-left: auto; margin-right: 0; ><div class='pageNumber'></div> <div>/</div><div class='totalPages'></div></div>
         // `
      });


      await browser.close();

      // convertToBase64(pdf)
      return pdf

      // console.log("PDF Buffer starting");
      // let options = {
      //     format: 'A4', path: 'result1.pdf',
      // };
      // // let file = { content: "<h1>Welcome to html-pdf-node</h1>" };

      // let file = { content: HTML_SAMPLE };
      // await html_to_pdf.generatePdf(file, options).then(pdfBuffer => {
      //     // console.log("PDF Buffer:-", pdfBuffer);
      // }).catch(err => console.log(err))
      // console.log("PDF created");


   } catch (error) {
      console.log("Error:-", error);
   }
}

const execute1 = async () => {


   console.log("1111111111111")
   const browser = await puppeteer.launch({
      defaultViewport: {
         ...chromium.defaultViewport,
         width: 800
      },
      args: chromium.args.filter(arg => !arg.includes('--window-size=')),
    //   executablePath: await chromium.executablePath('/opt/nodejs/node_modules/@sparticuz/chromium/bin'),
    //   headless: chromium.headless
      headless: false,

   });
   console.log("456")

   const page = await browser.newPage();
   await page.setContent(htmlFailEle, { timeout: 0, waitUntil: 'networkidle0' });
   await page.waitForSelector('.export-wrapper');
   const exportWrapper = await page.$('.export-wrapper');
   const tables = await exportWrapper.$$('table');
   //   await documentHelper.adjustPDFTableWidth(exportWrapper, tables);
   console.log("464")
   const pdf = await page.pdf({
      path: 'result1234.pdf',
      format: 'Letter',
      margin: { top: '40px', right: '40px', bottom: '120px', left: '40px' },
      displayHeaderFooter: true,
      headerTemplate: `
          <style>#header, #footer { padding: 0 !important; }</style>
          <div></div>
      `,
      footerTemplate: `${footer || "<div></div>"}`
   });
   await browser.close();
   return pdf


}

const convertToBase64 = (content) => {
   let convtData = Buffer.from(content).toString('base64')
   downloadAsPDF(convtData)
}

const downloadAsPDF = (base64Content) => {
   const linkSource = `data:application/pdf;base64,${base64Content}`;
   window.open(linkSource);
   // const fileNameSave = "fileName" + "_.pdf";
   // downloadLink.href = linkSource;
   // downloadLink.download = fileNameSave;
   // downloadLink.click();

}

execute1()
